a = float(input('Nhập số thực a: '))
b = float(input('Nhập số thực b: '))
print('Tổng của 2 số thực ',a,',',b, 'vừa nhập = %0.2f'%(a+b))
print('Hiệu của 2 số thực ',a,',',b, 'vừa nhập = %0.2f'%(a-b))
print('Tích của 2 số thực ',a,',',b, 'vừa nhập = %0.2f'%(a*b))
print('Thương của 2 số thực ',a,',',b, 'vừa nhập = %0.2f'%(a/b))