print("Nhập thông tin sinh viên:")

ma_so = input("Mã số sinh viên: ")
ten = input("Tên sinh viên: ")
que_quan = input("Quê quán: ")
nam_sinh = input("Năm sinh: ")
diem_trung_binh = input("Điểm trung bình các năm học: ")
print("\nThông tin sinh viên đã nhập:")
print("Mã số sinh viên:", ma_so)
print("Tên sinh viên:", ten)
print("Quê quán:", que_quan)
print("Năm sinh:", nam_sinh)
print("Điểm trung bình các năm học:", diem_trung_binh)