x1 = float(input("Nhập hoành độ x1 của đỉnh A: "))
y1 = float(input("Nhập tung độ y1 của đỉnh A: "))
x2 = float(input("Nhập hoành độ x2 của đỉnh B: "))
y2 = float(input("Nhập tung độ y2 của đỉnh B: "))
x3 = float(input("Nhập hoành độ x3 của đỉnh C: "))
y3 = float(input("Nhập tung độ y3 của đỉnh C: "))
xG = round((x1 + x2 + x3) / 3, 2)
yG = round((y1 + y2 + y3) / 3, 2)
print(f"Tọa độ trọng tâm G của tam giác là: ({xG}, {yG})")