xA = int(input('xA = '))
yA = int(input('yA = '))
xB = int(input('xB = '))
yB = int(input('yB = '))
xC = int(input('xC = '))
yC = int(input('yC = '))
xG = round((xA + xB + xC)/3, 2)
yG = round((yA + yB + yC)/3, 2)
print(f'Tọa độ G({xG}, {yG})')