ma_sv = input('Nhập thông tin sinh viên\n\tMã số sinh viên: ')
ho_ten = input('\tHọ và tên: ')
que_quan = input('\tQuê quán: ')
nam_sinh = input('\tNăm sinh: ')
diem_trung_binh = input('\tĐiểm trung bình: ')
print('\nMã số sinh viên:', ma_sv)
print('Họ tên:', ho_ten)
print('Quê quán:', que_quan)
print('Năm sinh:', nam_sinh)
print('Điểm trung bình:', diem_trung_binh)