ma=int(input("nhap ma sinh vien: "))
ten=input("nhap ho va ten: ")
que=input("nhap que quan: ")
nam=int(input("nhap nam sinh: "))
diem=float(input("nhap diem trung binh cac nam hoc: "))
print("ma sinh vien: ",ma)
print("ho va ten sinh vien: ",ten)
print("que quan: ",que)
print("nam sinh: ",nam)
print("diem trung binh cac nam hoc: %0.2f"%diem)