x = float(input("Nhập tọa độ x: "))
y = float(input("Nhập tọa độ y: "))
z = float(input("Nhập tọa độ z: "))
oxy = (x, y, -z)
oxz = (x, -y, z)
oyz = (-x, y, z)
print("Điểm đối xứng qua mặt phẳng Oxy:", oxy)
print("Điểm đối xứng qua mặt phẳng Oxz:", oxz)
print("Điểm đối xứng qua mặt phẳng Oyz:", oyz)