a = float(input("Nhập a: "))
b = float(input("Nhập b: "))
c = float(input("Nhập c: "))
x = -b / (2 * a)
y = (4 * a * c - b**2) / (4 * a)
print("Tọa độ đỉnh của parabol là:(", round(x, 2), ",", round(y, 2),")")
