a = [2, -4, 1, 9, -3, 6, 3, -2, 6, 8]
tong = sum(a)
print(f"Tong cac phan tu cua danh sach: {tong}")
duong = [x for x in a if x > 0]
tong_duong = sum(duong)
so_luong_duong = len(duong)
print(f"Tong cac so duong: {tong_duong}")
print(f"So luong so duong: {so_luong_duong}")
vi_tri_am_dau = next((i for i, x in enumerate(a) if x < 0), -1)
print(f"Vi tri phan tu am dau tien: {vi_tri_am_dau}")
vi_tri_am_cuoi = next((i for i, x in reversed(list(enumerate(a))) if x < 0), -1)
print(f"Vị tris phần tử âm cuối cùng: {vi_tri_am_cuoi}")
vi_tri_duong_dau = next((i for i, x in enumerate(a) if x > 0), -1)
print(f"Vị trí phần tử dương cuối cùng: {vi_tri_duong_dau}")
vi_tri_duong_cuoi = next((i for i, x in reversed(list(enumerate(a))) if x > 0), -1)
print(f"Vị trí phần tử dương cuối cùng: {vi_tri_duong_cuoi}")
max_value = max(a)
vi_tri_max_cuoi = max(i for i, x in enumerate(a) if x == max_value)
print(f"Phần tử lớn nhất: {max_value}")
print(f"Vị trí phần tử lớn nhất cuối cùng: {vi_tri_max_cuoi}")
