msv = int(input("Mã số sinh viên của bạn : "))
ho_ten = input("Họ Tên của bạn : ")
que_quan = input("Quê quán của bạn: ")
nam_sinh = input("Năm Sinh của bạn: ")
dtb = float(input("Điểm Trung Bình của bạn: "))
print("-----------Thông Tin Sinh Viên-----------")
print("Mã Số Sinh Viên của bạn : ",msv)
print("Họ tên của bạn : ",ho_ten)
print("Quê Quán của bạn : ",que_quan)
print("Năm sinh của bạn : ",nam_sinh)
print("Điểm Trung Bình của bạn: ",dtb)
print("----------------END----------------------")
