x1 = float(input("Nhập hoành độ x1 đỉnh A: "))
y1 = float(input("Nhập tung độ y1 đỉnh A: "))
x2 = float(input("Nhập hoành độ x2 đỉnh B: "))
y2 = float(input("Nhập tung độ y2 đỉnh B: "))
x3 = float(input("Nhập hoành độ x3 đỉnh C: "))
y3 = float(input("Nhập tung độ y3 đỉnh C: "))
xG = round((x1 + x2 + x3)/3,2)
yG = round((y1 + y2 + y3)/3,2)
print(f"Tọa độ trọng tâm G của tam giác là: ({xG}, {yG})")