mssv = input("Nhập mã số sinh viên: ")
ho_ten = input("Nhập họ tên: ")
que_quan = input("Nhập quê quán: ")
nam_sinh = input("Nhập năm sinh: ")
diem_trung_binh = float(input("Nhập điểm trung bình: "))

print("\nTHÔNG TIN SINH VIÊN:")
print(f"MSSV: {mssv}")
print(f"Họ tên: {ho_ten}")
print(f"Quê quán: {que_quan}")
print(f"Năm sinh: {nam_sinh}")
print(f"Điểm trung bình: {diem_trung_binh:.2f}")